### ISSUE TITLE
rtl_433 -U deprecated on Ubuntu 20 LTS

### ISSUE THREAD

**Issue by SebastianA** [egeoffrey/egeoffrey-service-rtl_433#1]
It seems that the parameters **-F json -U** are not compatible with that version and -U should be replaced with -M [timezone].

```
$ sudo rtl_433 -F json -U
[...]
UTC mode option (-U) is deprecated. Please use "-M utc".
```

**Comment by user2684** [comment]
Hi, thanks for reporting the issue! This should be fixed in the latest version (v1.0-17). After you upgrade, the configuration file will be upgraded as well with an additional setting called "arguments". By default it will be `-F json -U` but you can change it since it is no more hardcoded.

To upgrade you can run `sudo egeoffrey-cli update egeoffrey-service-rtl_433` and then `sudo egeoffrey-cli start`

Feel free to reopen this issue if not working as expected.
Thanks
